openai_api_key = "YourKey"
pinecone_api_key = "YourKey"
pinecone_environment = "YourENV"
pinecone_index = "YourIndex"
xata_api_key = "YourKey"
xata_db_url = "YourURL"
langchain_verbose = true
llm_model = "YourModel"
openrouter_api_key = "YourKey"
openrouter_api_base = "https://openrouter.ai/api/v1"
sensitivity_check = false
anonymous_allowed = true
password = "YourKey"